export function plannerHtml(session:string,nonce:string,cspSource:string,resource:(name:string)=>string):string {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${cspSource}; font-src ${cspSource}; script-src 'nonce-${nonce}'"><link rel="stylesheet" href="${resource('codicons/codicon.css')}"><link rel="stylesheet" href="${resource('rebase.css')}"></head><body data-session="${session}">
  <h1>Interactive Rebase</h1><p id="range"></p><p>Oldest first. Drag a commit onto another row to move it before that row. Move Up/Down or Alt+Arrow reorder with the keyboard.</p>
  <p id="status" role="status" aria-live="polite"></p><main><section aria-label="Ordered commits"><div id="commits" role="listbox" tabindex="0" aria-label="Rebase commits. Arrow keys select; Alt+Arrow reorders."></div></section>
  <section aria-labelledby="selected-title"><h2 id="selected-title">Selected commit</h2><p id="subject"></p><label>Action<select id="action" aria-describedby="action-help"><option value="pick">Pick</option><option value="reword">Reword</option><option value="edit">Edit</option><option value="squash">Squash</option><option value="fixup">Fixup</option><option value="drop">Drop</option></select></label><p id="action-help"></p>
  <div class="buttons"><button id="up">Move Up</button><button id="down">Move Down</button></div><button id="message">Edit Message</button><pre id="message-preview"></pre><p>Squash/Fixup need an earlier retained commit. Edit pauses for changes; Drop removes the commit from the rewritten range.</p></section></main>
  <footer><button id="review" class="primary">Review plan</button><button id="cancel">Cancel</button><button id="native">Use native planner</button></footer><p>Review opens a final confirmation naming the repository, original HEAD, base and ordered actions. Changed repository state requires a fresh review. Hooks and signing remain enabled.</p>
  <script nonce="${nonce}" src="${resource('rebase.js')}"></script></body></html>`;
}
