(() => {
  const api=acquireVsCodeApi(),session=document.body.dataset.session,byId=id=>document.getElementById(id);
  const list=byId('commits'),action=byId('action'),up=byId('up'),down=byId('down'),message=byId('message'),review=byId('review'),status=byId('status');
  let steps=[],selected,revision=0,busy=true,invalid=false,dragged,focusBeforeBusy;
  const actions={
    pick:{label:'Pick',codicon:'check',help:'Keep this commit and its message.'},
    reword:{label:'Reword',codicon:'edit',help:'Change this commit message; file content stays unchanged.'},
    edit:{label:'Edit',codicon:'debug-pause',help:'Pause at this commit so you can amend changes, then continue.'},
    squash:{label:'Squash',codicon:'fold-up',help:'Combine with the earlier retained commit and combine their messages.'},
    fixup:{label:'Fixup',codicon:'fold-up',help:'Combine with the earlier retained commit and keep its message.'},
    drop:{label:'Drop',codicon:'trash',help:'Remove this commit from the rewritten range.'}
  };
  const icon=name=>{const node=document.createElement('span');node.className=`codicon codicon-${name}`;node.setAttribute('aria-hidden','true');node.setAttribute('focusable','false');return node;};
  for(const [id,name] of [['up','arrow-up'],['down','arrow-down'],['message','edit'],['review','check']])byId(id).prepend(icon(name));
  const text=(className,value)=>{const node=document.createElement('span');node.className=className;node.textContent=value;return node;};
  const rememberFocus=()=>{const node=document.activeElement;if(node?.isConnected&&[list,action,up,down,message,review,byId('cancel'),byId('native')].includes(node))focusBeforeBusy=node;};
  const restoreFocus=()=>{const saved=focusBeforeBusy;focusBeforeBusy=undefined;if(!saved||(typeof document.hasFocus==='function'&&!document.hasFocus()))return;const active=document.activeElement;if(active&&active!==saved&&active!==document.body&&active.tagName!=='HTML'&&active.isConnected&&!active.disabled)return;(saved.isConnected&&!saved.disabled?saved:list).focus();};
  const send=(type,data={})=>{if(!busy||type==='ready')api.postMessage({type,session,revision,...data});};
  const controls=()=>{list.setAttribute('aria-busy',String(busy));const index=steps.findIndex(step=>step.oid===selected),step=steps[index];action.disabled=busy||!step;up.disabled=busy||index<=0;down.disabled=busy||index<0||index>=steps.length-1;message.disabled=busy||step?.action!=='reword';review.disabled=busy||invalid||!steps.length;byId('cancel').disabled=busy;byId('native').disabled=busy;for(const row of list.children){row.disabled=busy;row.draggable=!busy;}};
  const select=oid=>{selected=oid;const step=steps.find(item=>item.oid===oid);if(!step)return;list.setAttribute('aria-activedescendant',`commit-${oid}`);for(const row of list.children)row.setAttribute('aria-selected',String(row.dataset.oid===oid));byId('selected-title').textContent=`Selected: ${oid.slice(0,10)}`;byId('subject').textContent=step.subject;action.value=step.action;byId('action-help').textContent=(actions[step.action]||actions.pick).help;byId('message-preview').textContent=step.message||'';controls();};
  const render=()=>{list.replaceChildren();for(let index=0;index<steps.length;index++){const step=steps[index],row=document.createElement('button'),meta=actions[step.action]||actions.pick;row.id=`commit-${step.oid}`;row.className=`commit ${step.action}`;row.dataset.oid=step.oid;row.setAttribute('role','option');row.setAttribute('tabindex','-1');row.setAttribute('aria-label',`${index+1} of ${steps.length}, ${step.action}, ${step.subject}, ${step.oid}`);const identity=text('commit-identity',''),badge=text('action-badge','');badge.append(icon(meta.codicon),text('action-label',meta.label));const sha=text('commit-sha',step.oid.slice(0,8));sha.title=step.oid;identity.append(text('commit-order',`${index+1}.`),badge,sha);row.append(identity,text('commit-subject',step.subject));row.addEventListener('click',()=>{if(!busy){select(step.oid);list.focus();}});row.addEventListener('dragstart',event=>{if(busy){event.preventDefault();return;}dragged=step.oid;event.dataTransfer.setData('text/plain',step.oid);event.dataTransfer.effectAllowed='move';select(step.oid);});row.addEventListener('dragover',event=>{if(!busy&&dragged&&dragged!==step.oid){event.preventDefault();event.dataTransfer.dropEffect='move';}});row.addEventListener('drop',event=>{event.preventDefault();if(!busy&&dragged&&steps.some(item=>item.oid===dragged)){send('move',{oid:dragged,target:step.oid});dragged=undefined;}});row.addEventListener('dragend',()=>{dragged=undefined;});list.append(row);}if(!steps.some(step=>step.oid===selected))selected=steps[0]?.oid;select(selected);};
  list.addEventListener('keydown',event=>{if(busy){if(['ArrowUp','ArrowDown','Home','End'].includes(event.key))event.preventDefault();return;}if(!steps.length)return;const index=steps.findIndex(step=>step.oid===selected);if(event.altKey&&['ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();send('step',{oid:selected,direction:event.key==='ArrowUp'?'up':'down'});return;}let next=index;if(event.key==='ArrowDown')next=Math.min(steps.length-1,index+1);else if(event.key==='ArrowUp')next=Math.max(0,index-1);else if(event.key==='Home')next=0;else if(event.key==='End')next=steps.length-1;else return;event.preventDefault();select(steps[next].oid);list.setAttribute('aria-activedescendant',`commit-${selected}`);list.children[next].scrollIntoView?.({block:'nearest'});});
  up.addEventListener('click',()=>send('step',{oid:selected,direction:'up'}));down.addEventListener('click',()=>send('step',{oid:selected,direction:'down'}));action.addEventListener('change',()=>send('action',{oid:selected,action:action.value}));message.addEventListener('click',()=>send('message',{oid:selected}));review.addEventListener('click',()=>send('review'));byId('cancel').addEventListener('click',()=>send('cancel'));byId('native').addEventListener('click',()=>send('native'));
  window.addEventListener('message',event=>{const data=event.data;if(!data||data.session!==session)return;if(data.type==='state'){steps=data.steps;revision=data.revision;invalid=Boolean(data.error);status.textContent=data.error||'';byId('range').textContent=data.range;render();}else if(data.type==='busy'){if(data.busy&&!busy)rememberFocus();busy=data.busy;controls();if(!busy)restoreFocus();}else if(data.type==='error')status.textContent=data.message;});
  controls();send('ready');
})();
